### ISSUE TITLE
How to only search for signs

### ISSUE THREAD

**Issue by ntimo** [SimonOrJ/CoreProtect-Lookup-Web-Interface#6]
Hi there,
I was just reading the new realse notes witch sound really amazing. And was trying to test out the new system of displaying the text of a sign? But how do I only search for a sign? And how do I then get the text displayed. 

Thx
Timo

**Comment by chuushi** [comment]
You can search for `minecraft:standing_sign` or `minecraft:wall_sign` to get the lookup information for signs.  This was always a feature (since I don't remember when...), but it recently just added the sign texture from the game.

On all non-empty sign results, there will be a little arrow on the block column.  You can just click that, and the table will expand to show the results with signs.

![image](https://cloud.githubusercontent.com/assets/13530989/17790496/b24b6658-6564-11e6-99e6-713dfa843934.png)
